import { ArrowUpRight, Award, Workflow, Terminal, Tent, GraduationCap, ScanEye, Mail, Phone, MapPin, Github, Linkedin, Send } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { experiences, projects, skillGroups, profileLinks } from './portfolio-data';
import { usePortfolioText } from './portfolio-settings';

export function SocialLinks() {
 return <div className="social-links"><a className="social-link" href={profileLinks.linkedin} target="_blank" rel="noopener noreferrer" aria-label="LinkedIn"><Linkedin size={17}/></a><a className="social-link" href={profileLinks.github} target="_blank" rel="noopener noreferrer" aria-label="GitHub"><Github size={17}/></a><a className="social-link" href={`mailto:${profileLinks.email}`} aria-label="Email"><Mail size={17}/></a></div>;
}
function Tags({items}: {items:string[]}) {return <div className="tags">{items.map(item=><span className="tag" key={item}>{item}</span>)}</div>;}
function SectionHeading({number,label,title}: {number:string;label:string;title:string}) {return <div className="section-header"><div><p className="eyebrow">{label}</p><h2>{title}</h2></div><span className="section-number">/{number}</span></div>;}
export default function PortfolioSections() {
 const t=usePortfolioText();
 const icons: Record<string, typeof Workflow>={workflow:Workflow,terminal:Terminal,camp:Tent,education:GraduationCap,vision:ScanEye};
 return <>
  <section id="experiences" className="portfolio-section"><div className="portfolio-wrap"><SectionHeading number="01" label={t('Mon parcours','My journey')} title={t('Expérience professionnelle','Professional experience')}/>{experiences.map(exp=><article className="experience-row" key={exp.company}><div><h3>{exp.company}</h3><p className="muted-copy">{exp.location==='Tunisie'?t('Tunisie','Tunisia'):exp.location}</p><p className="muted-copy">{t(exp.period[0],exp.period[1])}</p></div><div><h4>{t(exp.role[0],exp.role[1])}</h4><ul>{exp.points.map(point=><li key={point[0]}>{t(point[0],point[1])}</li>)}</ul><Tags items={exp.tech}/></div></article>)}</div></section>
  <section id="projects" className="portfolio-section"><div className="portfolio-wrap"><SectionHeading number="02" label={t('De l’idée à la réalisation','From idea to delivery')} title={t('Projets sélectionnés','Selected projects')}/><div className="project-grid">{projects.map(project=>{const Icon=icons[project.icon]||Workflow;return <article className="bento-tile project-item" key={project.title}><div className="flex items-center justify-between"><Icon className="project-icon" size={25}/><span className="muted-copy">{project.year}</span></div><div><p className="eyebrow mb-3">{t(project.category[0],project.category[1])}</p><h3>{project.title}</h3></div><p className="muted-copy">{t(project.description[0],project.description[1])}</p><Tags items={project.tech}/></article>;})}</div><Button asChild variant="outline" className="mt-6 rounded-xl"><a href={profileLinks.github} target="_blank" rel="noopener noreferrer"><Github size={16}/>{t('Explorer mon GitHub','Explore my GitHub')}<ArrowUpRight size={16}/></a></Button></div></section>
  <section id="skills" className="portfolio-section"><div className="portfolio-wrap"><SectionHeading number="03" label={t('Expertise technique','Technical expertise')} title={t('Les outils, au service du résultat.','The right tools. Real results.')}/><div className="skills-grid">{skillGroups.map(group=><article className="bento-tile skill-item" key={group.title[0]}><h3 className="tile-heading">{t(group.title[0],group.title[1])}</h3><Tags items={group.skills}/></article>)}</div></div></section>
  <section id="education" className="portfolio-section"><div className="portfolio-wrap"><SectionHeading number="04" label={t('Apprendre & progresser','Learning & growing')} title={t('Formation & certifications','Education & certifications')}/><div className="education-grid"><article className="bento-tile"><p className="eyebrow">Sept. 2021 — {t('Janv.','Jan')} 2025</p><h3>{t('Ingénieur en informatique','Computer engineering')}</h3><p className="muted-copy">ESPRIT · Ariana, {t('Tunisie','Tunisia')}</p></article><article className="bento-tile"><p className="eyebrow">Sept. 2018 — {t('Juin','Jun')} 2021</p><h3>{t('Licence Électronique, Électrotechnique & Automatique','Bachelor in Electronics, Electrotechnics & Automation')}</h3><p className="muted-copy">FSM · Monastir, {t('Tunisie','Tunisia')}</p></article></div><div className="certifications"><p><Award className="text-primary" size={20}/>Generative AI for Java and Spring Development</p><p><Award className="text-primary" size={20}/>Advanced Spring Cloud Microservices & Deployment with Docker</p></div></div></section>
  <section id="contact" className="portfolio-section"><div className="portfolio-wrap contact-grid"><div><p className="eyebrow">{t('Et si on travaillait ensemble ?','Let’s build something together')}</p><h2 className="contact-title">{t('Votre prochain projet.','Your next project.')}<br/><span className="text-primary">{t('Notre prochaine conversation.','Our next conversation.')}</span></h2><p className="muted-copy">{t('Ouvert aux opportunités Full Stack Java/Angular et DevOps. Parlons de vos besoins et de ce que nous pouvons construire ensemble.','Open to Full Stack Java/Angular and DevOps opportunities. Let’s discuss your needs and what we can build together.')}</p><div className="contact-details"><a href={`mailto:${profileLinks.email}`}><Mail size={18}/>{profileLinks.email}</a><a href="tel:+21622623703"><Phone size={18}/>+216 22 623 703</a><p><MapPin size={18}/>Ariana, {t('Tunisie','Tunisia')}</p></div><SocialLinks/></div><form className="contact-form" onSubmit={event=>{event.preventDefault(); const data=new FormData(event.currentTarget);window.location.href=`mailto:${profileLinks.email}?subject=${encodeURIComponent('Portfolio — '+String(data.get('name')))}&body=${encodeURIComponent(String(data.get('message'))+'\n\n'+String(data.get('name'))+'\n'+String(data.get('email')))}`;}}><div><label htmlFor="contact-name">{t('Votre nom','Your name')}</label><Input id="contact-name" name="name" autoComplete="name" placeholder={t('Nom et prénom','Full name')} required/></div><div><label htmlFor="contact-email">{t('Votre email','Your email')}</label><Input id="contact-email" name="email" autoComplete="email" type="email" placeholder="vous@entreprise.com" required/></div><div><label htmlFor="contact-message">{t('Votre message','Your message')}</label><Textarea id="contact-message" name="message" rows={5} placeholder={t('Parlons de votre projet ou de votre opportunité…','Tell me about your project or opportunity…')} required/></div><Button type="submit" className="rounded-xl"><Send size={16}/>{t('Préparer mon email','Prepare my email')}</Button><p className="muted-copy">{t('Ouvre votre application de messagerie ; vous confirmez l’envoi.','Opens your email application; you confirm sending.')}</p></form></div></section>
 </>;
}
